"use client";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000/api/v1";
type Refund = { id:string; requested_amount:string; reason:string; status:string; customer:{name:string;email:string}; order:{order_number:string}; order_item:{id:string;product_name:string}; decision?:{outcome:string;reason_code:string;reason:string;ai_result:Record<string,unknown>}; audit_logs?:Array<{event_type:string;message:string}> };

export default function Home(){
  const [requests,setRequests]=useState<Refund[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  const [form,setForm]=useState({customer_email:"amina.bello@example.test",order_number:"WO-DEMO-001",order_item_id:"",requested_amount:"120.00",reason:"The item arrived as expected but I would like a refund."});
  async function load(){const r=await fetch(`${API}/refunds/requests/`); if(r.ok)setRequests(await r.json());}
  useEffect(()=>{load()},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await fetch(`${API}/refunds/requests/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.detail||JSON.stringify(data));setMessage(`Decision: ${data.decision?.outcome}. ${data.decision?.reason}`);setRequests(x=>[data,...x]);}catch(err){setMessage(String(err))}finally{setLoading(false)}}
  return <main><h1>Worknoon Refund Support</h1><p className="muted">AI-assisted customer refund workflow with deterministic policy enforcement.</p><div className="grid"><section className="card"><h2>Customer refund request</h2><form onSubmit={submit}><label>Email<input value={form.customer_email} onChange={e=>setForm({...form,customer_email:e.target.value})}/></label><div className="row"><label>Order number<input value={form.order_number} onChange={e=>setForm({...form,order_number:e.target.value})}/></label><label>Order item UUID<input value={form.order_item_id} onChange={e=>setForm({...form,order_item_id:e.target.value})}/></label></div><div className="row"><label>Amount<input value={form.requested_amount} onChange={e=>setForm({...form,requested_amount:e.target.value})}/></label></div><label>Reason<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={loading}>{loading?"Processing…":"Submit refund request"}</button></form>{message&&<p className="request"><strong>{message}</strong></p>}<p className="muted">For a seeded demo request, copy its item UUID from the dashboard below.</p></section><section className="card"><h2>Support dashboard</h2>{requests.length===0?<p className="muted">No requests yet.</p>:requests.slice(0,15).map(x=><div className="request" key={x.id}><span className="badge">{x.status}</span><strong> {x.order.order_number}</strong><div>{x.customer.name} · ${x.requested_amount}</div><div className="muted">{x.order_item.product_name} · {x.reason}</div>{x.decision&&<div className="muted">Decision: {x.decision.outcome} · {x.decision.reason_code}<br/>{x.decision.reason}</div>}</div>)}</section></div></main>
}
